project:
  home: /home/cclab
  user : cclab
  
cluster:
  master: 127.0.0.1
  worker1: 
    ip: 172.16.0.111
    id: cclab
    pw: cclab
  worker2: 
    ip: 172.16.0.112
    id: cclab
    pw: cclab

cilium-hubble:
  url: 10.110.139.142
  port: 80 # 4245

kubearmor:
  url: 10.107.65.121
  port: 32767
